### ISSUE TITLE
Private keypair doesn't save in SSM

### ISSUE THREAD

**Issue by paulmis** [udondan/cdk-ec2-key-pair#181]
Version `3.3.2`. I'm generating a keypair as follows:

```
const cloudFrontKeyPair = new KeyPair(this, 'CloudFrontKeyPair', {
      name: 'resources-' + environmentPrefix,
      secretPrefix: <prefix>
      exposePublicKey: true,
      publicKeyFormat: PublicKeyFormat.PEM
    });
```

However, the private key isn't saved in SSM. The synthed cdk has the following statement:

```
  DemoServiceCloudFrontKeyPairEC2KeyPairresourcesdev<...>:
    Type: Custom::EC2-Key-Pair
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - EC2KeyNameManagerLambda<...>
          - Arn
      Name: resources-dev
      Description: ""
      KmsPrivate: alias/aws/secretsmanager
      KmsPublic: alias/aws/secretsmanager
      PublicKey: ""
      StorePublicKey: false
      ExposePublicKey: true
      PublicKeyFormat: PEM
      RemoveKeySecretsAfterDays: 0
      SecretPrefix: <prefix>
      StackName: <stack>
      Tags:
        CreatedByCfnCustomResource: CFN::Resource::Custom::EC2-Key-Pair
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: <prefix>/EC2-Key-Pair-resources-dev/Default
```

but no `AWS::SSM`-type statements.
