### ISSUE TITLE
Tagging doesn't work

### ISSUE THREAD

**Issue by ilko-rbi** [udondan/cdk-ec2-key-pair#22]
Hi,

I'm trying to add some tags to the generated secret in the SecretsManager and somehow can't get it to work in python.  Any help will be highly appreciated.

Thanks!

The code is:

```python
from aws_cdk import core
from cdk_ec2_key_pair import KeyPair


class KeyPairTestStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        KeyPair(
            scope=self,
            id="hh",
            name="mykey",
            tags={
                "tag1": "value1",
                "tag2": "value2"
            }
        )


ENV_CC = core.Environment(account="xxx", region="eu-central-1")
app = core.App()
KeyPairTestStack(app, "myteststack", env=ENV_CC)
app.synth()
```
cdk synth generates me only "Created By" tag:
```yaml
Resources:
  hhEC2KeyPairmykeyEDB74C8E:
    Type: Custom::EC2-Key-Pair
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - EC2KeyNameManagerLambdaBE629145
          - Arn
      Name: mykey
      Description: ""
      KeyLength: 2048
      Kms: alias/aws/secretsmanager
      RemovePrivateKeyAfterDays: 0
      SecretPrefix: ec2-private-key/
      StackName: myteststack
      Tags:
        CreatedBy: CFN::Resource::Custom::EC2-Key-Pair
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: myteststack/hh/EC2-Key-Pair-mykey/Default
  EC2KeyPairManagerPolicyEBBC1576:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ec2:CreateKeyPair
              - ec2:DeleteKeyPair
              - ec2:DescribeKeyPairs
            Effect: Allow
            Resource: "*"
          - Action: secretsmanager:ListSecrets
            Effect: Allow
            Resource: "*"
          - Action:
              - secretsmanager:CreateSecret
              - secretsmanager:TagResource
            Condition:
              StringLike:
                aws:RequestTag/CreatedBy: CFN::Resource::Custom::EC2-Key-Pair
            Effect: Allow
            Resource: "*"
          - Action:
              - secretsmanager:DeleteResourcePolicy
              - secretsmanager:DeleteSecret
              - secretsmanager:DescribeSecret
              - secretsmanager:GetResourcePolicy
              - secretsmanager:ListSecretVersionIds
              - secretsmanager:PutResourcePolicy
              - secretsmanager:PutSecretValue
              - secretsmanager:RestoreSecret
              - secretsmanager:UntagResource
              - secretsmanager:UpdateSecret
              - secretsmanager:UpdateSecretVersionStage
            Condition:
              StringLike:
                secretsmanager:ResourceTag/CreatedBy: CFN::Resource::Custom::EC2-Key-Pair
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      Description: Used by Lambda CFN-Resource-Custom-EC2-Key-Pair, which is a custom CFN resource, managing EC2 Key Pairs
      ManagedPolicyName: myteststack-CFN-Resource-Custom-EC2-Key-Pair
      Path: /
    Metadata:
      aws:cdk:path: myteststack/EC2-Key-Pair-Manager-Policy/Resource
  EC2KeyPairManagerRoleB243C519:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Used by Lambda CFN-Resource-Custom-EC2-Key-Pair, which is a custom CFN resource, managing EC2 Key Pairs
      ManagedPolicyArns:
        - Ref: EC2KeyPairManagerPolicyEBBC1576
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: myteststack-CFN-Resource-Custom-EC2-Key-Pair
    Metadata:
      aws:cdk:path: myteststack/EC2-Key-Pair-Manager-Role/Resource
  EC2KeyNameManagerLambdaBE629145:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterse50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2S3BucketEAEA5028
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2S3VersionKeyE22B7168
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2S3VersionKeyE22B7168
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - EC2KeyPairManagerRoleB243C519
          - Arn
      Runtime: nodejs10.x
      Description: "Custom CFN resource: Manage EC2 Key Pairs"
      FunctionName: myteststack-CFN-Resource-Custom-EC2-Key-Pair
      Timeout: 180
    DependsOn:
      - EC2KeyPairManagerRoleB243C519
    Metadata:
      aws:cdk:path: myteststack/EC2-Key-Name-Manager-Lambda/Resource
      aws:asset:path: asset.e50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2.zip
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.73.0,@aws-cdk/assets=1.73.0,@aws-cdk/aws-applicationautoscaling=1.73.0,@aws-cdk/aws-autoscaling-common=1.73.0,@aws-cdk/aws-cloudformation=1.73.0,@aws-cdk/aws-cloudwatch=1.73.0,@aws-cdk/aws-codeguruprofiler=1.73.0,@aws-cdk/aws-ec2=1.73.0,@aws-cdk/aws-efs=1.73.0,@aws-cdk/aws-events=1.73.0,@aws-cdk/aws-iam=1.73.0,@aws-cdk/aws-kms=1.73.0,@aws-cdk/aws-lambda=1.73.0,@aws-cdk/aws-logs=1.73.0,@aws-cdk/aws-s3=1.73.0,@aws-cdk/aws-s3-assets=1.73.0,@aws-cdk/aws-sns=1.73.0,@aws-cdk/aws-sqs=1.73.0,@aws-cdk/aws-ssm=1.73.0,@aws-cdk/cloud-assembly-schema=1.73.0,@aws-cdk/core=1.73.0,@aws-cdk/cx-api=1.73.0,@aws-cdk/region-info=1.73.0,jsii-runtime=Python/3.7.7
    Metadata:
      aws:cdk:path: myteststack/CDKMetadata/Default
Parameters:
  AssetParameterse50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2S3BucketEAEA5028:
    Type: String
    Description: S3 bucket for asset "e50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2"
  AssetParameterse50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2S3VersionKeyE22B7168:
    Type: String
    Description: S3 key for asset version "e50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2"
  AssetParameterse50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2ArtifactHash56A19821:
    Type: String
    Description: Artifact hash for asset "e50a85ce3b59c30e167fe1a3d4457c163479976cbc4d00d9db586785fa06d5a2"
```
